name: ci

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: bun
        run: bun install --frozen-lockfile
      - name: bun format:check
        run: bun format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: bun
        run: bun install --frozen-lockfile
      - name: bun lint
        run: bun lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: bun
        run: bun install --frozen-lockfile
      - name: bun tsc
        run: bun tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: bun
        run: bun install --frozen-lockfile
      - name: bun test
        run: bun test
